### ISSUE TITLE
__parameterNames__ were not replaced with $ServiceName

### ISSUE THREAD

**Issue by wpschaub** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#5]
In the release script, **parameterNames** were not replaced with $ServiceName. Is this expected?
Email: Feedback on "Release management workflow migrator", 2015-12-15

**Comment by DanielBMann9000** [comment]
A bit more background on this for anyone interested:

For a given Action, arguments can contain parameter tokens, like `-SomeParameter __Parameter Value__`, with *`__Parameter Value__` being a token. The tool correctly identifies these and turns them into PowerShell variables (so `__Parameter Value__` => `$ParameterValue`)

It's been brought to our attention that the _Command_ field also supports parameter tokens! The tool does not currently account for that, so if you tried to use a Command like `__Foo__.exe`, where `__Foo__` was a token to be replaced later, the `__Foo__` token would not be replaced in the output, so the generated PowerShell script would try to execute `__Foo__.exe` instead of `$Foo.exe`

For what it's worth, this should be a fairly rare scenario.

This will be fixed!
